### ISSUE TITLE
Model the env200 in URDF

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/autoware#11]
Create a URDF model for the StreetDrone Nissan ENV200

For reference there is a StreetDrone Twizy model [here](https://github.com/streetdrone-home/SD-TwizyModel)

- [x] see if there is an online CAD model we can use to convert to URDF
- [x] contact StreetDrone to see if they have a URDF model for the van
- [x] look into alternatives if there are no pre-existing CAD files online or from SD
    - [x] look into 3d scanning the van
    - [x] look into using a generic minivan cad model, and converting it to URDF 
- [ ] test the URDF model with the sensors in the correct position with Gazebo / Autoware

See [this](https://www.notion.so/monashcav/13-08-23-Articulated-Robotics-tute-notes-3f0f52eec29e4ad7b1aa89fda1ee59b6) doc for more info on URDF

If you need to test Autoware with a simulator, read [here](https://github.com/Monash-Connected-Autonomous-Vehicle/autoware/wiki/Autoware).

**Comment by suey147** [comment]
I've come across a few CAD models of the Nissan e-NV200, but it seems the pricing is not suitable for our current needs. 
https://sketchfab.com/3d-models/nissan-e-nv200-van-2022-db60a9a208e846a09c849f4411739cbb 
https://3dmodels.org/3d-models/nissan-e-nv200-van-2014/ 
https://www.cgtrader.com/3d-models/car/suv/nissan-e-nv200-van-2014 

also Found a free 3d obj of  Nissan nv 200 dhl van, which looks similar to an env200. could use this if we can't find other CAD files to convert.
https://grabcad.com/library/nissan-nv200-dhl-van-1

**Comment by dylan-gonzalez** [comment]
The last one seems promising (unless Streetdrone doesn't have one already)

**Comment by dylan-gonzalez** [comment]
> Have we contacted or found out if Streetdrone has a URDF model already? I see that checkbox has been marked off

I believe @suey147 has made a post on the zendesk. Here is a [guide](https://www.notion.so/monashcav/StreetDrone-Help-Desk-74474274c31b46308efdb8b4dc5b5d56) on how to access the zendesk.

> I don't have much experience on URDF but I'm studying up on the link of more info on URDF and will prepare to work on this from tomorrow onwards

It might be good if you and @suey147 organise a working session to create a URDF from this model: https://grabcad.com/library/nissan-nv200-dhl-van-1

**Comment by adar0024** [comment]
![Screenshot 2023-12-05 125724](https://github.com/Monash-Connected-Autonomous-Vehicle/autoware/assets/110092516/ab818f12-e45d-45c3-bf68-9304ac93c24e)
I have accessed the zendesk but I'm not sure the post is here?

**Comment by adar0024** [comment]
Suey did make the post but it was made on a different account. We posted it on the MCAV account now.

We are now working on creating a URDF of aforementioned model

**Comment by andSoHenceforth** [comment]
https://www.cgtrader.com/free-3d-models/car/car/nissan-e-nv200

**Comment by andSoHenceforth** [comment]
@suey147 

StreetDrone has replied to us with an attachment of files that include the e-NV200 URDF model! No need to convert anything to URDF anymore :)

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/autoware/assets/110092516/86706b0d-c169-4d39-8dff-67dfa8c305c7)

**Comment by dylan-gonzalez** [comment]
Closing this issue ^
