### ISSUE TITLE
CARLA x Autoware test on Twizy

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/autoware#32]

**Comment by davbt** [comment]
This [resolved issue](https://github.com/hatem-darweesh/op_bridge/issues/27) is pretty much a tutorial for setting up Carla x Autoware (i.e. set a path in Rviz then the bridge publishes Autoware Ackermann Control Messages in ROS, and thus, can control the Twizy).  


If you want to run the Carla x Autoware in one machine, and SD-VehicleInterface in another, you'll need to run the following commands on both machines' terminals:
```
export ROS_LOCALHOST_ONLY=2 
export ROS_DOMAIN_ID=2      # This can be any number, but must be the same for all machines of interest
```

**Comment by dylan-gonzalez** [comment]
is there a repo for this?

**Comment by davbt** [comment]
You'll need  3 [repos by hatem-darweesh](https://github.com/orgs/autowarefoundation/discussions/2828#discussioncomment-7929757). I managed to get it working on _the Beast_.

**Comment by dylan-gonzalez** [comment]
It would be good if this could all be packaged in some way into one repository so that it's reproducible.
I've just made a new [repo](https://github.com/Monash-Connected-Autonomous-Vehicle/streetdrone-hil) for running HIL demos with the Streetdrone vehicles as I need to set up a CARLA HIL demo for a unit. 

Would be neat if (when you get time) make a branch for carla-autoware-zenoh bridge HIL demo and could probably add those 3 repos ^ as submodules?

**Comment by dylan-gonzalez** [comment]
Also great work!!

**Comment by davbt** [comment]
> Would be neat if (when you get time) make a branch for carla-autoware-zenoh bridge HIL demo and could probably add those 3 repos ^ as submodules?

I was actually just using the 3 repos by Hatem, without the [autoware_carla_launch](https://github.com/evshary/autoware_carla_launch/tree/humble) (which uses zenoh). If you want to control multiple vehicles using a single Carla simulator, we'll need to use that. There is a way to for zenoh to publish to ros2 topics apparently, refer to [this resolved issue](https://github.com/evshary/autoware_carla_launch/issues/25)

**Comment by davbt** [comment]
Also Rviz + Carla should be done on a machine with at least 32 gb ram (i.e. not the SD Alienware Laptop). Maybe we could use one of the hives or something. Then we could publish to ROS topics via LAN.

**Comment by dylan-gonzalez** [comment]
Yeah no stress whatever works

**Comment by davbt** [comment]
Rviz (on ~8 fps) + Carla running on the SD Alienware: https://drive.google.com/file/d/1ywcLC-7fMzx-sukkRjqpWB_ePQO9rQ5b/view?usp=share_link
