### ISSUE TITLE
(Twizy) Collect launch files for sensors

### ISSUE THREAD

**Issue by davbt** [Monash-Connected-Autonomous-Vehicle/autoware#40]
- x2 people
**Goal**: Collate/create/find launch files (`.xml` or `.launch.py`) for launching sensors

Ensure sensors work and publish correct Message Types:
- [x] LiDAR as `sensor_msgs/PointCloud2.msg` 
- [x] IMU as `sensor_msgs/Imu.msg`
- [x] Cameras as `sensor_msgs/Image.msg`
- [x] GNSS-INS as 	`sensor_msgs/msg/NavSatFix.msg`

Launch file tasks:
- [x] Create a `camera.launch.xml` or `.py` launch file
- [x] Create a `lidar.launch.xml` or `.py` launch file 

Helpful resources
- [Twizy Sensor's Notion Doc](https://www.notion.so/monashcav/Twizy-Sensors-e2b70a26516740739f63d73ed0e81767)
- [Autoware's *Sensor launch*](https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/#sensor-launch)
- [*Sensor component design*](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/sensing/#high-level-architecture) details more about each sensor
- Consult this [unresolved issue](https://github.com/Monash-Connected-Autonomous-Vehicle/autoware/issues/7) for more details about what's currently working

**Comment by davbt** [comment]
SSH
```
ssh mcav@192.168.11.127
```

**Comment by davbt** [comment]
For Velodyne, Alienware Laptop (via ethernet or wirelessly) and LIDAR (via ethernet) must be connected to in-built router.

Command to launch:
`ros2 launch velodyne velodyne-all-nodes-VLP16-launch.py`

Or using 2 commands in different terminals
First terminal:
```sh
ros2 launch velodyne_driver velodyne_driver_node-VLP16-launch.py
```

Second terminal:
```sh
ros2 launch velodyne_pointcloud velodyne_transform_node-VLP16-launch.py
```

See also [twizy_sensor_kit_launch](https://github.com/dtonda8/twizy_sensor_kit_launch) for settings when connected to router.

For direct ethernet connection, make sure you run the following on the laptop after connection (you might need to change `eth` interface):
```bash
sudo ip addr add 192.168.1.100/24 dev enp68s0
sudo ip link set enp68s0 up
```

#### Visualising 
Use RViz (type `rviz2` on terminal):
1. Set `Fixed Frame` to `velodyne`
2. Click "Add" on the bottom left and add the `PointClound2` topic (if you can't see this then the lidar is not properly working)

**Comment by davbt** [comment]
[Docs for starting the Vehicle Interface](https://github.com/Monash-Connected-Autonomous-Vehicle/twist_controller/blob/main/README.md#using-sd-vehicleinterface-with-twist-controller-the-following-is-mainly-for-the-twizy)

**Comment by jxcksonli** [comment]
http://wiki.ros.org/video_stream_opencv
https://github.com/clydemcqueen/h264_image_transport

**Comment by davbt** [comment]
#### Current GStreamer files
https://github.com/Monash-Connected-Autonomous-Vehicle/stream_sample_camera_gmsl/tree/stream_directly

#### Testing GStreamer locally
Server 
```sh
# From file
cat test1.h264 | gst-launch-1.0 -e fdsrc ! h264parse ! \
    avdec_h264 ! videoconvert ! videorate ! video/x-raw,framerate=30/1 ! \
    x264enc tune=zerolatency bitrate=1000 speed-preset=ultrafast ! \
    video/x-h264,profile=baseline ! rtph264pay ! udpsink \
    host=<CHANGE TO YOUR IP> port=5000

# From mac
gst-launch-1.0 avfvideosrc device-index=1 ! videoscale ! videoconvert ! x264enc tune=zerolatency bitrate=3000 speed-preset=ultrafast ! h264parse ! rtph264pay ! udpsink host=<CHANGE TO YOUR IP> port=5000
```

Client 
```sh
# Get stream 
gst-launch-1.0 -e udpsrc port=5000 caps="application/x-rtp" ! rtpjitterbuffer \
    ! rtph264depay ! avdec_h264 ! fpsdisplaysink
```

For cameras, either:
1. Publish to ROS from PX 2
2. Stream and publish to ROS form Alienware Laptop

PX 2 SSH:
1. Connect to StreetDrone wifi
2. SSH
```sh
ssh nvidia@192.168.1.180
```

[Sample files and stream repo](https://github.com/Monash-Connected-Autonomous-Vehicle/stream_sample_camera_gmsl/tree/stream_directly) (switch to stream_directly)

**Comment by davbt** [comment]
[gscam2](https://github.com/clydemcqueen/gscam2) might be useful

**Comment by jxcksonli** [comment]
Attempt using gscam2, located in
mcav@twizy-x86:~/dbat/test1$

Ran using
ros2 run gscam2 gscam_main --ros-args --remap /image_raw:=/my_camera/image_raw --params-file src/gscam2/gscam_params.yaml -p camera_info_url:=file://$PWD/src/gscam2/cfg/my_camera.ini

Error: Failed to Pause Stream, Check GScam config

**Comment by davbt** [comment]
[ROS answer on h264 streaming](https://answers.ros.org/question/379644/compress-image-topic-with-h264-streaming-for-low-bandwidth-connection/) i.e. what we want

**Comment by davbt** [comment]
Hi guys gscam2 works! I've tried in my laptop. The tasks for you guys is to:

- [x] Create a `camera.launch.xml` or `.py` launch file that runs the script. If you remember from last Thursday, gscam required a local workspace, so modify the script to source the correct workspace location.
- [x] Create a `lidar.launch.xml` or `.py` launch file to launch the velodyne that we tested a 2 weeks ago

We won't need to create launch files for IMU since that's already done by the vehicle interface

#### `gscam` details
- [Installation](https://github.com/clydemcqueen/gscam2?tab=readme-ov-file#install-and-build). Then
```sh
source install/local_setup.bash && export GSCAM_CONFIG='udpsrc port=5000 caps="application/x-rtp" ! rtpjitterbuffer ! rtph264depay ! avdec_h264 ! videoconvert' && ros2 run gscam2 gscam_main --ros-args -p sync_sink:=true -p preroll:=true
```

[ROS 2 tutorial on creating launch files](https://docs.ros.org/en/humble/Tutorials/Intermediate/Launch/Creating-Launch-Files.html)

**Comment by davbt** [comment]
Fortunately, the [default lidar.launch.xml](https://github.com/autowarefoundation/sample_sensor_kit_launch/blob/main/sample_sensor_kit_launch/launch/lidar.launch.xml) pretty much managed the launching. Just needed to tweak the default parameters, our resulting sensor kit launch is [here](https://github.com/dtonda8/twizy_sensor_kit_launch/tree/main).

To try out (as of our Autoware's current directory):
```bash
cd ~/twizy/autoware.twizy
source install/setup.bash
ros2 launch twizy_sensor_kit_launch sensing.launch.xml vehicle_mirror_param_file:=/home/mcav/twizy/autoware.twizy/src/vehicle/twizy_vehicle_launch/twizy_vehicle_description/config/mirror.param.yaml vehicle_param_file:=/home/mcav/twizy/autoware.twizy/src/vehicle/twizy_vehicle_launch/twizy_vehicle_description/config/vehicle_info.param.yaml
```

 The working tweaks of the Lidar settings at http://192.168.1.201/ and the Alienware Laptop's Wired interface are shown on [twizy_sensor_kit_launch readme](https://github.com/dtonda8/twizy_sensor_kit_launch/tree/main#twizy_sensor_kit_launch)
