### ISSUE TITLE
(ENV200) Automate start up

### ISSUE THREAD

**Issue by davbt** [Monash-Connected-Autonomous-Vehicle/autoware#47]
I noticed it's quite tedious to start the computer of the Van (networking, ssh prep etc.).
I think it's worth investigating various ways to optimise this, we could either try to properly install ubuntu or look at start up scripts.

Skills: Shell scripting, Linux OS & a bit of Networking

**Comment by davbt** [comment]
Hi all. I think this task is worth looking at first before Autoware installation:
Options:
1. Try to use the Desktop Image of [Ubuntu 22](https://releases.ubuntu.com/jammy/) → We then won't need to use xRDP
- I found a way to install ubuntu-desktop on terminal: https://phoenixnap.com/kb/how-to-install-a-gui-on-ubuntu
2. Create a `sh` script that sets up networking, ssh etc. That is, a random UA software member should be able to use Ubuntu normally (with internet access) without needing to know the settings 
Lmk if you need assistance. Post updates/logs, helpful resources and anything else useful on this GitHub Issue.

**Comment by LJ2533** [comment]
I haven't been able to come in for the past week but I'll be in tomorrow to work on this task.
Having the desktop version of Ubuntu should improve ease of use so I plan on implementing that. I'll update tomorrow once this is complete.

**Comment by davbt** [comment]
Thanks for the update! I'll be on campus till 2pm tmr, let me know if you're facing any issues.

**Comment by LJ2533** [comment]
Jin and I have installed the desktop image for the van and its working nicely. We did a quick test of the NVidia drivers as well, as that was went wrong last time and there were no problems there either.

**Comment by davbt** [comment]
Nice work guys! How's the networking though? Is it easy to connect to wifi after `sudo reboot`? If so, we can close this issue.

Edit: Networking is working!
