### ISSUE TITLE
(Twizy) Start PX 2 Camera streaming remotely

### ISSUE THREAD

**Issue by davbt** [Monash-Connected-Autonomous-Vehicle/autoware#49]
Currently, the camera stream needs to be started locally (i.e. log in to PX 2 and start camera stream). 

We want to start the camera stream automatically. 
- [ ] Either use `ssh` via alienware laptop and run `~/Downloads/sender_alienware.sh` (previously tried)
- [ ] Or, start camera stream automatically on PX 2 boot up

While this is not necessary, this automation would save a lot of time

#### PX 2 Setup
Right now (as of July 9) the PX 2 is running the `~/Downloads/sender_alienware.sh` script (have a look at the script via ssh). it starts the camera and streams the feed to the alienware's ip.

```bash
/usr/local/driveworks/bin/sample_camera_gmsl --write-file="/dev/stdout" | \
    gst-launch-1.0 -e fdsrc ! h264parse ! avdec_h264 ! videoconvert ! \
    videorate ! video/x-raw,framerate=30/1 ! x264enc tune=zerolatency \
    bitrate=3000 speed-preset=ultrafast ! video/x-h264,profile=baseline ! \
    rtph264pay ! udpsink host=<alienware-ip> port=5000
```

Both the PX 2 and alieware is wired connected the the same router, so you can [SSH to PX 2](https://www.notion.so/monashcav/SSH-connection-to-the-PX2-10f4de03594043eba232c09950e4817e)

**Comment by davbt** [comment]
Hey Daniel, how's your progress so far?

This might be a good start of running the `sh` script without needing to login: https://askubuntu.com/questions/745933/execute-script-before-login

**Comment by hong0431** [comment]
Hi David,
Not too much, I'll have a lot more time to work on it and figure it out before tmr's meeting.

**Comment by hong0431** [comment]
We've tried multiple methods to get the camera automatically startup with no luck.

Link for different methods used for future reference:
https://www.squash.io/executing-bash-script-at-startup-in-ubuntu-linux/

**Comment by davbt** [comment]
Thanks @hong0431. I've created another task that's sort of related: https://github.com/orgs/Monash-Connected-Autonomous-Vehicle/projects/8/views/15?pane=issue&itemId=71519558

It's more research based, have a look at notion docs, github and link any useful info.

**Comment by dylan-gonzalez** [comment]
this shouldn't be too hard if you make a `systemd` service for it. https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd

**Comment by davbt** [comment]
I think @hong0431 tried the `systemd` service. We'll give it another shot tho.
